/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author u71744222177
 */
public class JDlgGpfUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMpvUsuarios
     */
    public JDlgGpfUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de usuário");
        setLocationRelativeTo(null);
        desabilitar();
    }

    public void desabilitar() {
        jTxtGpfCodigo.setEnabled(false);
        jTxtGpfNome.setEnabled(false);
        jTxtGpfApelido.setEnabled(false);
        jFmtGpfData.setEnabled(false);
        jFmtGpfCpf.setEnabled(false);
        jFmtGpfData.setEnabled(false);
        jCboGpfNivel.setEnabled(false);
        jPwfGpfSenha.setEnabled(false);
        jChbGpfAtivo.setEnabled(false);
        jBtnGpfConfirmar.setEnabled(false);
        jBtnGpfCancelar.setEnabled(false);
        jBtnGpfIncluir.setEnabled(true);
        jBtnGpfAlterar.setEnabled(true);
        jBtnGpfExcluir.setEnabled(true);
        jBtnGpfPesquisar.setEnabled(true);
    }

    public void habilitar() {
        jTxtGpfCodigo.setEnabled(true);
        jTxtGpfNome.setEnabled(true);
        jTxtGpfApelido.setEnabled(true);
        jFmtGpfData.setEnabled(true);
        jFmtGpfCpf.setEnabled(true);
        jFmtGpfData.setEnabled(true);
        jCboGpfNivel.setEnabled(true);
        jPwfGpfSenha.setEnabled(true);
        jChbGpfAtivo.setEnabled(true);
        jBtnGpfConfirmar.setEnabled(true);
        jBtnGpfCancelar.setEnabled(true);
        jBtnGpfIncluir.setEnabled(false);
        jBtnGpfAlterar.setEnabled(false);
        jBtnGpfExcluir.setEnabled(false);
        jBtnGpfPesquisar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblGpfCodigo = new javax.swing.JLabel();
        jTxtGpfCodigo = new javax.swing.JTextField();
        jLblGpfNome = new javax.swing.JLabel();
        jTxtGpfNome = new javax.swing.JTextField();
        jLblGpfApelido = new javax.swing.JLabel();
        jTxtGpfApelido = new javax.swing.JTextField();
        jLblGpfCpf = new javax.swing.JLabel();
        jFmtGpfCpf = new javax.swing.JFormattedTextField();
        jLblGpfData = new javax.swing.JLabel();
        jFmtGpfData = new javax.swing.JFormattedTextField();
        jLblGpfNivel = new javax.swing.JLabel();
        jCboGpfNivel = new javax.swing.JComboBox<>();
        jLblGpfSenha = new javax.swing.JLabel();
        jPwfGpfSenha = new javax.swing.JPasswordField();
        jChbGpfAtivo = new javax.swing.JCheckBox();
        jBtnGpfIncluir = new javax.swing.JButton();
        jBtnGpfAlterar = new javax.swing.JButton();
        jBtnGpfExcluir = new javax.swing.JButton();
        jBtnGpfConfirmar = new javax.swing.JButton();
        jBtnGpfPesquisar = new javax.swing.JButton();
        jBtnGpfCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblGpfCodigo.setText("Código");

        jLblGpfNome.setText("Nome");

        jLblGpfApelido.setText("Apelido");

        jLblGpfCpf.setText("CPF");

        jLblGpfData.setText("Data de Nascimento");

        jLblGpfNivel.setText("Nível");

        jCboGpfNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLblGpfSenha.setText("Senha");

        jPwfGpfSenha.setText("jPasswordField1");

        jChbGpfAtivo.setText("Ativo");

        jBtnGpfIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnGpfIncluir.setText("Incluir");
        jBtnGpfIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfIncluirActionPerformed(evt);
            }
        });

        jBtnGpfAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnGpfAlterar.setText("Alterar");
        jBtnGpfAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfAlterarActionPerformed(evt);
            }
        });

        jBtnGpfExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnGpfExcluir.setText("Excluir");
        jBtnGpfExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfExcluirActionPerformed(evt);
            }
        });

        jBtnGpfConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnGpfConfirmar.setText("Confirmar");
        jBtnGpfConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfConfirmarActionPerformed(evt);
            }
        });

        jBtnGpfPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnGpfPesquisar.setText("Pesquisar");
        jBtnGpfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfPesquisarActionPerformed(evt);
            }
        });

        jBtnGpfCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnGpfCancelar.setText("Cancelar");
        jBtnGpfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtGpfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblGpfCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblGpfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTxtGpfNome)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtGpfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblGpfApelido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblGpfCpf)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jFmtGpfCpf)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLblGpfData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFmtGpfData))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblGpfNivel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jCboGpfNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblGpfSenha)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPwfGpfSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jChbGpfAtivo))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnGpfIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGpfAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGpfExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGpfConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGpfCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jBtnGpfPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblGpfCodigo)
                    .addComponent(jLblGpfNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGpfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGpfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblGpfApelido)
                    .addComponent(jLblGpfCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGpfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtGpfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblGpfData)
                    .addComponent(jLblGpfNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtGpfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboGpfNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblGpfSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfGpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbGpfAtivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGpfIncluir)
                    .addComponent(jBtnGpfAlterar)
                    .addComponent(jBtnGpfExcluir)
                    .addComponent(jBtnGpfConfirmar)
                    .addComponent(jBtnGpfPesquisar)
                    .addComponent(jBtnGpfCancelar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGpfIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnGpfIncluirActionPerformed

    private void jBtnGpfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnGpfCancelarActionPerformed

    private void jBtnGpfAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfAlterarActionPerformed
        habilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGpfAlterarActionPerformed

    private void jBtnGpfConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfConfirmarActionPerformed
        desabilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGpfConfirmarActionPerformed

    private void jBtnGpfExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Confirma exclusão do usuário ?",
                "Seleciona a opção", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnGpfExcluirActionPerformed

    private void jBtnGpfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Entre com o código do usuário");
    }//GEN-LAST:event_jBtnGpfPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgGpfUsuarios dialog = new JDlgGpfUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGpfAlterar;
    private javax.swing.JButton jBtnGpfCancelar;
    private javax.swing.JButton jBtnGpfConfirmar;
    private javax.swing.JButton jBtnGpfExcluir;
    private javax.swing.JButton jBtnGpfIncluir;
    private javax.swing.JButton jBtnGpfPesquisar;
    private javax.swing.JComboBox<String> jCboGpfNivel;
    private javax.swing.JCheckBox jChbGpfAtivo;
    private javax.swing.JFormattedTextField jFmtGpfCpf;
    private javax.swing.JFormattedTextField jFmtGpfData;
    private javax.swing.JLabel jLblGpfApelido;
    private javax.swing.JLabel jLblGpfCodigo;
    private javax.swing.JLabel jLblGpfCpf;
    private javax.swing.JLabel jLblGpfData;
    private javax.swing.JLabel jLblGpfNivel;
    private javax.swing.JLabel jLblGpfNome;
    private javax.swing.JLabel jLblGpfSenha;
    private javax.swing.JPasswordField jPwfGpfSenha;
    private javax.swing.JTextField jTxtGpfApelido;
    private javax.swing.JTextField jTxtGpfCodigo;
    private javax.swing.JTextField jTxtGpfNome;
    // End of variables declaration//GEN-END:variables

}
