/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author u06454182185
 */
public class JDlgGpfClientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgGpfClientes
     */
    public JDlgGpfClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedores");
        setLocationRelativeTo(null);
        desabilitar();
    }

    public void desabilitar() {
        jTxtGpfCodigo.setEnabled(false);
        jTxtGpfNome.setEnabled(false);
        jFmtGpfCPF.setEnabled(false);
        jFmtGpfRG.setEnabled(false);
        jFmtGpfDataDeNascimento.setEnabled(false);
        jTxtGpfEmail.setEnabled(false);
        jFmtGpfTelefone.setEnabled(false);
        jFmtGpfCelular.setEnabled(false);
        jFmtGpfCEP.setEnabled(false);
        jFmtGpfCEP.setEnabled(false);
        jTxtGpfEndereco.setEnabled(false);
        jTxtGpfNumero.setEnabled(false);
        jTxtGpfBairro.setEnabled(false);
        jTxtGpfCidade.setEnabled(false);
        jTxtGpfEstado.setEnabled(false);
        jTxtGpfComplemento.setEnabled(false);
        jChbGpfAtivo.setEnabled(false);
        jBtnGpfConfirmar.setEnabled(false);
        jBtnGpfCancelar.setEnabled(false);
        jBtnGpfIncluir.setEnabled(true);
        jBtnGpfAlterar.setEnabled(true);
        jBtnGpfExcluir.setEnabled(true);
        jBtnGpfPesquisar.setEnabled(true);
    }

    public void habilitar() {
        jTxtGpfCodigo.setEnabled(true);
        jTxtGpfNome.setEnabled(true);
        jFmtGpfCPF.setEnabled(true);
        jFmtGpfRG.setEnabled(true);
        jFmtGpfDataDeNascimento.setEnabled(true);
        jTxtGpfEmail.setEnabled(true);
        jFmtGpfTelefone.setEnabled(true);
        jFmtGpfCelular.setEnabled(true);
        jFmtGpfCEP.setEnabled(true);
        jFmtGpfCEP.setEnabled(true);
        jTxtGpfEndereco.setEnabled(true);
        jTxtGpfNumero.setEnabled(true);
        jTxtGpfBairro.setEnabled(true);
        jTxtGpfCidade.setEnabled(true);
        jTxtGpfEstado.setEnabled(true);
        jTxtGpfComplemento.setEnabled(true);
        jChbGpfAtivo.setEnabled(true);
        jBtnGpfConfirmar.setEnabled(true);
        jBtnGpfCancelar.setEnabled(true);
        jBtnGpfIncluir.setEnabled(false);
        jBtnGpfAlterar.setEnabled(false);
        jBtnGpfExcluir.setEnabled(false);
        jBtnGpfPesquisar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblGpfCodigo = new javax.swing.JLabel();
        jTxtGpfCodigo = new javax.swing.JTextField();
        jLblGpfNome = new javax.swing.JLabel();
        jTxtGpfNome = new javax.swing.JTextField();
        jLblGpfCPF = new javax.swing.JLabel();
        jLblGpfRG = new javax.swing.JLabel();
        jLblGpfDataDeNascimento = new javax.swing.JLabel();
        jFmtGpfRG = new javax.swing.JFormattedTextField();
        jFmtGpfDataDeNascimento = new javax.swing.JFormattedTextField();
        jFmtGpfCPF = new javax.swing.JFormattedTextField();
        jLblGpfEmail = new javax.swing.JLabel();
        jTxtGpfEmail = new javax.swing.JTextField();
        jLblGpfTelefone = new javax.swing.JLabel();
        jFmtGpfTelefone = new javax.swing.JFormattedTextField();
        jLblGpfCelular = new javax.swing.JLabel();
        jFmtGpfCelular = new javax.swing.JFormattedTextField();
        jLblGpfCEP = new javax.swing.JLabel();
        jFmtGpfCEP = new javax.swing.JFormattedTextField();
        jLblGpfEndereco = new javax.swing.JLabel();
        jTxtGpfEndereco = new javax.swing.JTextField();
        jLblGpfNumero = new javax.swing.JLabel();
        jTxtGpfNumero = new javax.swing.JTextField();
        jLblGpfBairro = new javax.swing.JLabel();
        jTxtGpfBairro = new javax.swing.JTextField();
        jLblGpfCidade = new javax.swing.JLabel();
        jTxtGpfCidade = new javax.swing.JTextField();
        jLblGpfEstado = new javax.swing.JLabel();
        jTxtGpfEstado = new javax.swing.JTextField();
        jLblGpfComplemento = new javax.swing.JLabel();
        jTxtGpfComplemento = new javax.swing.JTextField();
        jChbGpfAtivo = new javax.swing.JCheckBox();
        jBtnGpfConfirmar = new javax.swing.JButton();
        jBtnGpfPesquisar = new javax.swing.JButton();
        jBtnGpfCancelar = new javax.swing.JButton();
        jBtnGpfIncluir = new javax.swing.JButton();
        jBtnGpfAlterar = new javax.swing.JButton();
        jBtnGpfExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblGpfCodigo.setText("Código");

        jLblGpfNome.setText("Nome");

        jLblGpfCPF.setText("CPF");

        jLblGpfRG.setText("RG");

        jLblGpfDataDeNascimento.setText("Data de Nascimento");

        jLblGpfEmail.setText("Email");

        jLblGpfTelefone.setText("Telefone");

        jLblGpfCelular.setText("Celular");

        jLblGpfCEP.setText("CEP");

        jLblGpfEndereco.setText("Endereço");

        jLblGpfNumero.setText("Número");

        jLblGpfBairro.setText("Bairro");

        jLblGpfCidade.setText("Cidade");

        jLblGpfEstado.setText("Estado");

        jLblGpfComplemento.setText("Complemento");

        jChbGpfAtivo.setText("Ativo");

        jBtnGpfConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnGpfConfirmar.setText("Confirmar");
        jBtnGpfConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfConfirmarActionPerformed(evt);
            }
        });

        jBtnGpfPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnGpfPesquisar.setText("Pesquisar");
        jBtnGpfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfPesquisarActionPerformed(evt);
            }
        });

        jBtnGpfCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnGpfCancelar.setText("Cancelar");
        jBtnGpfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfCancelarActionPerformed(evt);
            }
        });

        jBtnGpfIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnGpfIncluir.setText("Incluir");
        jBtnGpfIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfIncluirActionPerformed(evt);
            }
        });

        jBtnGpfAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnGpfAlterar.setText("Alterar");
        jBtnGpfAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfAlterarActionPerformed(evt);
            }
        });

        jBtnGpfExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnGpfExcluir.setText("Excluir");
        jBtnGpfExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblGpfEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtGpfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLblGpfEmail))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblGpfTelefone)
                                            .addComponent(jFmtGpfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtGpfCelular)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblGpfCelular)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtGpfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblGpfCEP)))
                            .addComponent(jLblGpfComplemento)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLblGpfCodigo)
                                            .addComponent(jLblGpfCPF)
                                            .addComponent(jTxtGpfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                            .addComponent(jFmtGpfCPF))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblGpfNome)
                                            .addComponent(jTxtGpfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLblGpfRG)
                                                .addGap(76, 76, 76)
                                                .addComponent(jLblGpfDataDeNascimento))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jFmtGpfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jFmtGpfDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtGpfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLblGpfNumero)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLblGpfBairro)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTxtGpfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxtGpfBairro)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtGpfCidade)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblGpfCidade)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblGpfEstado)
                                    .addComponent(jTxtGpfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtGpfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jChbGpfAtivo)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnGpfIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGpfAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGpfExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGpfConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGpfCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jBtnGpfPesquisar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblGpfCodigo)
                    .addComponent(jLblGpfNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtGpfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGpfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblGpfCPF)
                    .addComponent(jLblGpfRG)
                    .addComponent(jLblGpfDataDeNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtGpfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtGpfDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtGpfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblGpfEmail)
                    .addComponent(jLblGpfTelefone)
                    .addComponent(jLblGpfCelular)
                    .addComponent(jLblGpfCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGpfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtGpfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtGpfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtGpfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblGpfEndereco)
                    .addComponent(jLblGpfNumero)
                    .addComponent(jLblGpfBairro)
                    .addComponent(jLblGpfCidade)
                    .addComponent(jLblGpfEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGpfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGpfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGpfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGpfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGpfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblGpfComplemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGpfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbGpfAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGpfIncluir)
                    .addComponent(jBtnGpfAlterar)
                    .addComponent(jBtnGpfExcluir)
                    .addComponent(jBtnGpfConfirmar)
                    .addComponent(jBtnGpfPesquisar)
                    .addComponent(jBtnGpfCancelar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGpfConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfConfirmarActionPerformed
        desabilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGpfConfirmarActionPerformed

    private void jBtnGpfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Entre com o código do cliente");
    }//GEN-LAST:event_jBtnGpfPesquisarActionPerformed

    private void jBtnGpfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnGpfCancelarActionPerformed

    private void jBtnGpfIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnGpfIncluirActionPerformed

    private void jBtnGpfAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfAlterarActionPerformed
        habilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGpfAlterarActionPerformed

    private void jBtnGpfExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Confirma exclusão do cliente ?",
                "Seleciona a opção", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnGpfExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgGpfClientes dialog = new JDlgGpfClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGpfAlterar;
    private javax.swing.JButton jBtnGpfCancelar;
    private javax.swing.JButton jBtnGpfConfirmar;
    private javax.swing.JButton jBtnGpfExcluir;
    private javax.swing.JButton jBtnGpfIncluir;
    private javax.swing.JButton jBtnGpfPesquisar;
    private javax.swing.JCheckBox jChbGpfAtivo;
    private javax.swing.JFormattedTextField jFmtGpfCEP;
    private javax.swing.JFormattedTextField jFmtGpfCPF;
    private javax.swing.JFormattedTextField jFmtGpfCelular;
    private javax.swing.JFormattedTextField jFmtGpfDataDeNascimento;
    private javax.swing.JFormattedTextField jFmtGpfRG;
    private javax.swing.JFormattedTextField jFmtGpfTelefone;
    private javax.swing.JLabel jLblGpfBairro;
    private javax.swing.JLabel jLblGpfCEP;
    private javax.swing.JLabel jLblGpfCPF;
    private javax.swing.JLabel jLblGpfCelular;
    private javax.swing.JLabel jLblGpfCidade;
    private javax.swing.JLabel jLblGpfCodigo;
    private javax.swing.JLabel jLblGpfComplemento;
    private javax.swing.JLabel jLblGpfDataDeNascimento;
    private javax.swing.JLabel jLblGpfEmail;
    private javax.swing.JLabel jLblGpfEndereco;
    private javax.swing.JLabel jLblGpfEstado;
    private javax.swing.JLabel jLblGpfNome;
    private javax.swing.JLabel jLblGpfNumero;
    private javax.swing.JLabel jLblGpfRG;
    private javax.swing.JLabel jLblGpfTelefone;
    private javax.swing.JTextField jTxtGpfBairro;
    private javax.swing.JTextField jTxtGpfCidade;
    private javax.swing.JTextField jTxtGpfCodigo;
    private javax.swing.JTextField jTxtGpfComplemento;
    private javax.swing.JTextField jTxtGpfEmail;
    private javax.swing.JTextField jTxtGpfEndereco;
    private javax.swing.JTextField jTxtGpfEstado;
    private javax.swing.JTextField jTxtGpfNome;
    private javax.swing.JTextField jTxtGpfNumero;
    // End of variables declaration//GEN-END:variables

}
