/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author u71744222177
 */
public class JDlgGpfProdutos extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMpvUsuarios
     */
    public JDlgGpfProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produtos");
        setLocationRelativeTo(null);
        desabilitar();
    }

    public void desabilitar() {
        jTxtGpfCodigo.setEnabled(false);
        jTxtGpfNome.setEnabled(false);
        jTxtGpfDescricao.setEnabled(false);
        jFmtGpfPrecoCusto.setEnabled(false);
        jFmtGpfPrecoVenda.setEnabled(false);
        jTxtGpfQuantidade.setEnabled(false);
        jChbGpfAtivo.setEnabled(false);
        jBtnGpfConfirmar.setEnabled(false);
        jBtnGpfCancelar.setEnabled(false);
        jBtnGpfIncluir.setEnabled(true);
        jBtnGpfAlterar.setEnabled(true);
        jBtnGpfExcluir.setEnabled(true);
        jBtnGpfPesquisar.setEnabled(true);
    }

    public void habilitar() {
        jTxtGpfCodigo.setEnabled(true);
        jTxtGpfNome.setEnabled(true);
        jTxtGpfDescricao.setEnabled(true);
        jFmtGpfPrecoCusto.setEnabled(true);
        jFmtGpfPrecoVenda.setEnabled(true);
        jTxtGpfQuantidade.setEnabled(true);
        jChbGpfAtivo.setEnabled(true);
        jBtnGpfConfirmar.setEnabled(true);
        jBtnGpfCancelar.setEnabled(true);
        jBtnGpfIncluir.setEnabled(false);
        jBtnGpfAlterar.setEnabled(false);
        jBtnGpfExcluir.setEnabled(false);
        jBtnGpfPesquisar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblGpfCodigo = new javax.swing.JLabel();
        jTxtGpfCodigo = new javax.swing.JTextField();
        jLblGpfNome = new javax.swing.JLabel();
        jTxtGpfNome = new javax.swing.JTextField();
        jLblGpfDescricao = new javax.swing.JLabel();
        jTxtGpfDescricao = new javax.swing.JTextField();
        jLblGpfPrecoCusto = new javax.swing.JLabel();
        jFmtGpfPrecoCusto = new javax.swing.JFormattedTextField();
        jLblGpfPrecoVenda = new javax.swing.JLabel();
        jLblGpfQuantidade = new javax.swing.JLabel();
        jChbGpfAtivo = new javax.swing.JCheckBox();
        jBtnGpfIncluir = new javax.swing.JButton();
        jBtnGpfAlterar = new javax.swing.JButton();
        jBtnGpfExcluir = new javax.swing.JButton();
        jBtnGpfConfirmar = new javax.swing.JButton();
        jBtnGpfPesquisar = new javax.swing.JButton();
        jBtnGpfCancelar = new javax.swing.JButton();
        jFmtGpfPrecoVenda = new javax.swing.JFormattedTextField();
        jTxtGpfQuantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblGpfCodigo.setText("Código");

        jLblGpfNome.setText("Nome");

        jLblGpfDescricao.setText("Descrição");

        jLblGpfPrecoCusto.setText("Preço Custo");

        jLblGpfPrecoVenda.setText("Preço Venda");

        jLblGpfQuantidade.setText("Quantidade");

        jChbGpfAtivo.setText("Ativo");

        jBtnGpfIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnGpfIncluir.setText("Incluir");
        jBtnGpfIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfIncluirActionPerformed(evt);
            }
        });

        jBtnGpfAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnGpfAlterar.setText("Alterar");
        jBtnGpfAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfAlterarActionPerformed(evt);
            }
        });

        jBtnGpfExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnGpfExcluir.setText("Excluir");
        jBtnGpfExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfExcluirActionPerformed(evt);
            }
        });

        jBtnGpfConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnGpfConfirmar.setText("Confirmar");
        jBtnGpfConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfConfirmarActionPerformed(evt);
            }
        });

        jBtnGpfPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnGpfPesquisar.setText("Pesquisar");
        jBtnGpfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfPesquisarActionPerformed(evt);
            }
        });

        jBtnGpfCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnGpfCancelar.setText("Cancelar");
        jBtnGpfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGpfCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtGpfDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtGpfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblGpfCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblGpfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtGpfNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnGpfIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGpfAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGpfExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGpfConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGpfCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jBtnGpfPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtGpfPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblGpfPrecoCusto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblGpfPrecoVenda)
                            .addComponent(jFmtGpfPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblGpfQuantidade)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtGpfQuantidade)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblGpfDescricao)
                            .addComponent(jChbGpfAtivo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblGpfCodigo)
                    .addComponent(jLblGpfNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGpfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGpfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblGpfDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtGpfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblGpfPrecoCusto)
                            .addComponent(jLblGpfQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtGpfPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblGpfPrecoVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtGpfPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtGpfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(jChbGpfAtivo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGpfIncluir)
                    .addComponent(jBtnGpfAlterar)
                    .addComponent(jBtnGpfExcluir)
                    .addComponent(jBtnGpfConfirmar)
                    .addComponent(jBtnGpfPesquisar)
                    .addComponent(jBtnGpfCancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGpfIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnGpfIncluirActionPerformed

    private void jBtnGpfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnGpfCancelarActionPerformed

    private void jBtnGpfAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfAlterarActionPerformed
        habilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGpfAlterarActionPerformed

    private void jBtnGpfConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfConfirmarActionPerformed
        desabilitar();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGpfConfirmarActionPerformed

    private void jBtnGpfExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Confirma exclusão do produto ?",
                "Seleciona a opção", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnGpfExcluirActionPerformed

    private void jBtnGpfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGpfPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Entre com o código do produto");
    }//GEN-LAST:event_jBtnGpfPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgGpfProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgGpfProdutos dialog = new JDlgGpfProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGpfAlterar;
    private javax.swing.JButton jBtnGpfCancelar;
    private javax.swing.JButton jBtnGpfConfirmar;
    private javax.swing.JButton jBtnGpfExcluir;
    private javax.swing.JButton jBtnGpfIncluir;
    private javax.swing.JButton jBtnGpfPesquisar;
    private javax.swing.JCheckBox jChbGpfAtivo;
    private javax.swing.JFormattedTextField jFmtGpfPrecoCusto;
    private javax.swing.JFormattedTextField jFmtGpfPrecoVenda;
    private javax.swing.JLabel jLblGpfCodigo;
    private javax.swing.JLabel jLblGpfDescricao;
    private javax.swing.JLabel jLblGpfNome;
    private javax.swing.JLabel jLblGpfPrecoCusto;
    private javax.swing.JLabel jLblGpfPrecoVenda;
    private javax.swing.JLabel jLblGpfQuantidade;
    private javax.swing.JTextField jTxtGpfCodigo;
    private javax.swing.JTextField jTxtGpfDescricao;
    private javax.swing.JTextField jTxtGpfNome;
    private javax.swing.JTextField jTxtGpfQuantidade;
    // End of variables declaration//GEN-END:variables

}
